# Generated by Django 4.0.1 on 2022-03-20 15:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/shop/category/%Y/%m/%d/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=300, verbose_name='ссылка')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.SlugField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='uploads/shop/items/%Y/%m/%d/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_apps_shop.category')),
            ],
        ),
    ]
