# Generated by Django 4.0.1 on 2022-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_news',
            name='image',
            field=models.ImageField(upload_to='media/category_news_pic/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news_objects',
            name='image',
            field=models.ImageField(upload_to='media/news_objects/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
