# Generated by Django 4.0.1 on 2022-02-06 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_apps_kinopoisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=6000),
        ),
    ]
