# Generated by Django 4.0.1 on 2022-02-06 12:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_apps_kinopoisk', '0002_alter_actor_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
